services:
  db:
    container_name: postgres_meteor
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=meteor
      - POSTGRES_DB=meteor
    volumes:
      - pgdata:/var/lib/popostgresql/data
    networks:
      - meteor_network
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 30s

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    environment:
      - CORS_ORIGIN=http://localhost:3001
      - BETTER_AUTH_SECRET=VDCrYEBWPVAdwmURuNRgvJDVd4iquQGw
      - BETTER_AUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:meteor@localhost:5432/meteor
    ports:
      - 3000:3000
    networks:
      - meteor_network
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    environment:
      - VITE_SERVER_URL=http://localhost:3000
    ports:
      - 3001:3001
    networks:
      - meteor_network

networks:
  meteor_network:
    external: true

volumes:
  pgdata:
